language: python

matrix:
  include:
  - os: linux
    dist: xenial
    python: 3.7
  - os: linux
    dist: xenial
    python: 3.8
  - os: osx
    language: generic

before_install:
- pip install poetry

install:
- poetry install

script:
- poetry run isort -rc -c --diff aiohomekit tests
- poetry run black aiohomekit tests --check --diff
- poetry run flake8 aiohomekit
- poetry run mypy aiohomekit
- poetry run coverage run -m pytest tests/

after_success:
- poetry run codecov
