stages:
- test
- deploy

language: python

before_install:
  - pip install poetry

  install:
  - poetry check
  - poetry install

  script:
  - poetry run isort -rc -c --diff aiohomekit tests
  - poetry run black aiohomekit tests --check --diff
  - poetry run flake8 aiohomekit
  - poetry run mypy aiohomekit
  - poetry run coverage run -m pytest tests/
  - poetry build

  after_success:
  - poetry run codecov

jobs:
  include:
  - os: linux
    dist: xenial
    python: 3.7

  - os: linux
    dist: xenial
    python: 3.8

  - os: osx
    language: generic

  - stage: deploy
    script: poetry build
    after_success: "true"
    deploy:
      - provider: script
        skip_cleanup: true
        script: poetry publish
        on:
          repo: Jc2k/aiohomekit
          tags: true

      - provider: releases
        skip_cleanup: true
        api_key:
          secure: rNGSRiM6AyV4Lnqf8GGmXrgUgOmSGiMOLmj3EMKkRyjY8vP44ffWeJ0Hq7XMxMWWBkZlpVbIgmMOAzYANCg+Oz6NC77RYKJ1eV+rcEyDFbhmEt3DHF1pfP0KmscVumQLb9MQcvgDW4jTUaFhE3211yNXZqYLIFjClHLwdwK/n0HM/BBLQ0i7WLBA1/hH1+Zmy35MA8yLiljLef05bDam5dygIDKbkcZuRBpcJLBOKiccUX848OKC8BaOlWrwCeP/B2fOKNRqKboGj+dqxar+JJbr8zT9mYm61migZ3/j6h+NKUZgXLPakFOP3foN8fF01Yt0noF7j11/dT4yHJLkdY1wxW749gY/uc2ZGbD1w8uKIMzx5Oh8hymSn3oQl5QWXDMEBSRwR7eGQalRMIjM+oGcAnZVV9GVgfMlVVwE7iFncFLPn4RJ20JsMnSJJErv8+FEw+vnrswvt7QZmzL2Ntij+WX52mDGBfoL8ft4HBBq3f+VUPjASeKcX7LxeihebY5xac8F8R6yL1sdpJxhq83L+vP5uodlsKKKPdgNtqLB1LOesjM7f7SFNWy8dRlAcnRIg05p6vq0D8SbOPxvP9bMVMq6wQzY6IJTsZxuav69X1JIBnfBd591r8LTiK1mTfcgjCNpK+IkYF/CsVRmFOkHBtUCcQE4irxeC/adq5E=
          file_glob: true
          file: dist/*
          on:
            repo: Jc2k/aiohomekit
            tags: true

env:
  global:
    secure: f6+wxomxvhJUDa17hknAs0ALMi8ZM8I6+qVQocIO7Rf+z6vR8I0/rsACH3U2DEy5OebbEzkz7RDPMGpytS81AmvwbgCABV9v2RMkxjtlVRN6ELUJh0vVSN1JftTxheEiZRpDFFcW4N2k72SMDF5bBqaXwfzRtYZNygufPOFrYez/HFOIbHqcf8gXErVHDlp4GIy9RmHTYntw6LnoXTKG8g4EULF45d9ut95Pq/TmVdqxsCi68oZ2jzIAPlfsQLqZUh7QethxqQwfWEnsEzYMiChjHgD/b/ecB0zzVZuoJEkxOE5uczmQ0oDggp7ya5MCzDm1cvEHJHMT7ZwWH9t5hWvPB56dC9z0mWJIkkYkIFz3lKmyxRrsUa+HttQK89tJ/YBkfNAM1fY5BWK7MBnvnfxe+9dp7ud30xWxm1E84/JrYjxjYEThrWAbzjvllDtBemGh5pJR1urF2WHtZ0wZ/6Y4O8cZyHH6lY+Grn5Vv3j7j5RGY9QrwIPO4mlppzK9bioroOejn+UoOLs54QDmdOF+a+KimDLXiau7+ezHGKdLOov1OBCF2dU73kNOn9a+Ym7sQyRCumqad+uzWqEuMwTiCrIPyls1Ot1MCaVyo/bKP+G09PYaOJJuZMdTIP+UNhM/5QR4AduHc4slDLxldkoroInzHyrk9Xwjq1dYaVE=
