stages:
- test
- deploy

language: python

before_install:
- pip install poetry

install:
- poetry check
- poetry install

script:
- poetry run isort -rc -c --diff aiohomekit tests
- poetry run black aiohomekit tests --check --diff
- poetry run flake8 aiohomekit tests
- poetry run mypy aiohomekit
- poetry run coverage run -m pytest tests/
- poetry build

after_success:
- poetry run codecov

jobs:
  include:
  - os: linux
    dist: xenial
    python: 3.7

  - os: linux
    dist: xenial
    python: 3.8

  - os: osx
    language: generic

  - stage: deploy
    dist: xenial
    python: 3.7
    script:
      - poetry config pypi-token.pypi $POETRY_PYPI_TOKEN_PYPI
      - poetry build
    after_success: "true"
    deploy:
      - provider: script
        skip_cleanup: true
        script: poetry publish
        on:
          repo: Jc2k/aiohomekit
          tags: true

      - provider: releases
        skip_cleanup: true
        api_key:
          secure: rNGSRiM6AyV4Lnqf8GGmXrgUgOmSGiMOLmj3EMKkRyjY8vP44ffWeJ0Hq7XMxMWWBkZlpVbIgmMOAzYANCg+Oz6NC77RYKJ1eV+rcEyDFbhmEt3DHF1pfP0KmscVumQLb9MQcvgDW4jTUaFhE3211yNXZqYLIFjClHLwdwK/n0HM/BBLQ0i7WLBA1/hH1+Zmy35MA8yLiljLef05bDam5dygIDKbkcZuRBpcJLBOKiccUX848OKC8BaOlWrwCeP/B2fOKNRqKboGj+dqxar+JJbr8zT9mYm61migZ3/j6h+NKUZgXLPakFOP3foN8fF01Yt0noF7j11/dT4yHJLkdY1wxW749gY/uc2ZGbD1w8uKIMzx5Oh8hymSn3oQl5QWXDMEBSRwR7eGQalRMIjM+oGcAnZVV9GVgfMlVVwE7iFncFLPn4RJ20JsMnSJJErv8+FEw+vnrswvt7QZmzL2Ntij+WX52mDGBfoL8ft4HBBq3f+VUPjASeKcX7LxeihebY5xac8F8R6yL1sdpJxhq83L+vP5uodlsKKKPdgNtqLB1LOesjM7f7SFNWy8dRlAcnRIg05p6vq0D8SbOPxvP9bMVMq6wQzY6IJTsZxuav69X1JIBnfBd591r8LTiK1mTfcgjCNpK+IkYF/CsVRmFOkHBtUCcQE4irxeC/adq5E=
        file_glob: true
        file: dist/*
        on:
          repo: Jc2k/aiohomekit
          tags: true

env:
  global:
    secure: VkjRPOfBiI0pJ+H6B6HEeDog1kJ/mSUgdM8c6VWxUFuqMIPAikSq7Y/nDJ5hB+5VA7coKw6cqaXfgqbt0VUMF291upJ7sllTXVrtAqbyQajq3OuG6xoeYjlwJH9at6KXKctEvNVPFIos/3G7xh3OpkpYVC+QsLxI56QTL/dTIUErNwttKK/fypEmIac0WvdvDrpRSjC8MIeRO60x93fDAR88nBRxOpNGuKviCWIXEpXs538x85D5lL/uk4yx0WnKjfmwAm6oKfsDjzijSG/PfrtDWVtnBM1VbbL22K4Qv5Xucgp15cnYwyNjHT+t6y8b773oD547XisIsIm1XX4M3i1FS7swcFUH3m1KXtYapWLDtK2DTVOUR/H0V5k4WpgQs0C8dloVWeg9EgXMwDIW+boWDafh7ermkp34/iy8wimNlhwbX0WUvK9LWEpTozdRWKxMmcEjf03Y6COBJ0xpEnaSairFHDiCX8PYUQX9SbzK3Xi6BWg3KcKpFJbzLZ/a40shzEJ1HH0buTbHFrCFCvgCIybR/4nMWBZKq3IW/UXZEVJbIudE1S3KTmicITEx8eG27/TG5xlLHAffYOEVO7jl3xyUW5XrnYlTZ/v6TqDCfszmSTOqJ2aMk6caeHQyWCcuKgUIHC1MmTQxgtyMKv8DAnwTelT5RlsRBbPfIIQ=
