#! env python

import json
import plistlib
import textwrap


plist = "/Applications/HomeKit Accessory Simulator.app/Contents/Frameworks/HAPAccessoryKit.framework/Versions/A/Resources/default.metadata.plist"
with open(plist, "rb") as fp:
    data  = plistlib.load(fp)

characteristics = {}

for char in data.get('Characteristics', []):
    name = char['Name'].replace(".", "_").replace(" ", "_").upper()

    c = characteristics[char['UUID']] = {
        'name': name,
        'description': char['Name'],
    }

    if char.get('Properties'):
        c['perms'] = []
        for perm in char.get('Properties'):
            if perm == "read":
                c['perms'].append("pr")
            if perm == "write":
                c['perms'].append("pw")
            if perm == "cnotify":
                c['perms'].append("ev")

    if char.get('Format'):
        c['format'] = char['Format']

    if char.get('Unit'):
        c['unit'] = char['Unit']

    if 'Constraints' not in char:
        continue

    constraints = char['Constraints']

    if constraints.get('MaximumValue'):
        c['max_value'] = constraints['MaximumValue']
    if constraints.get('MaximumValue'):
        c['min_value'] = constraints['MinimumValue']
    if constraints.get('StepValue'):
        c['step_value'] = constraints['StepValue']


with open("aiohomekit/model/characteristics/data.py", "w") as fp:
    fp.write(textwrap.dedent("""
    # AUTOGENERATED, DO NOT EDIT

    characteristics = 
    """).strip())
    fp.write(" " + json.dumps(characteristics, indent=4))
    fp.write("\n")
