name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v4
      - name: Get tag
        id: tag
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.11
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v5
        with:
          python-version: 3.11
          cache: "poetry"
      - name: Build a binary wheel and a source tarball
        run: poetry build
      - name: Store the distribution packages
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v4
        with:
          name: python-package-distributions
          path: dist/

  deploy_pypi:
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    runs-on: ubuntu-latest
    needs:
      - build
    name: >-
      Publish Python 🐍 distribution 📦 to PyPI
    environment:
      name: release
      url: https://pypi.org/p/aiohomekit

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # release/v1

  deploy_github:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for sigstore signing
      contents: write # for creating a release
    needs:
      - build
    name: >-
      Publish Python 🐍 distribution 📦 to GitHub
    environment:
      name: release
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Collected dists
        run: |
          tree dist
      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@f832326173235dcb00dd5d92cd3f353de3188e6c # v3.1.0
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl

      - name: GitHub Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2
        with:
          tag_name: ${{ needs.build.outputs.tag }}
          files: dist/**
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
