name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
      - name: Get tag
        id: tag
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.11
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v5
        with:
          python-version: 3.11
          cache: "poetry"
      - name: Build a binary wheel and a source tarball
        run: poetry build
      - name: Store the distribution packages
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: python-package-distributions
          path: dist/

  deploy_pypi:
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    runs-on: ubuntu-latest
    needs:
      - build
    name: >-
      Publish Python 🐍 distribution 📦 to PyPI
    environment:
      name: release
      url: https://pypi.org/p/aiohomekit

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # release/v1

  deploy_github:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for sigstore signing
      contents: write # for creating a release
    needs:
      - build
    name: >-
      Publish Python 🐍 distribution 📦 to GitHub
    environment:
      name: release
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Collected dists
        run: |
          tree dist
      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@790bc6befb9d733738f18d8f895854b453640ec9 # v3.5.0
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl

      - name: GitHub Release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v2
        with:
          tag_name: ${{ needs.build.outputs.tag }}
          files: dist/**
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
